/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-14 06:55:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"inane.ico\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>PRODUCTION STORE</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family:YuMincho,'Yu Mincho',serif;\r\n");
      out.write("\tcolor:#5a5a5a;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\ta:link {\r\n");
      out.write("\tcolor:#5a5a5a;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:visited {\r\n");
      out.write("\tcolor:#5a5a5a;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:hover {\r\n");
      out.write("\tcolor:#ac946c;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:active {\r\n");
      out.write("\tcolor:#cac6ae;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("\theight:80px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header h1 {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-top:30px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header ul {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tlist-style:;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header ul li {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menubar {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground-color:#000000;\r\n");
      out.write("\tcolor:#ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menubar ul {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("\tbackground-color:;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menubar ul li {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tline-height:10px;\r\n");
      out.write("\tfont-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t#menubar a:link {\r\n");
      out.write("\tcolor:#ffffff;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menubar a:visited {\r\n");
      out.write("\tcolor:#ffffff;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menubar a:hover {\r\n");
      out.write("\tcolor:#ac946c;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menubar a:active {\r\n");
      out.write("\tcolor:#cac6ae;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("#are {\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\ttext-align:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tbackground-color:#ffffff;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\theight:150px;\r\n");
      out.write("\tborder:1px solid #5a5a5a;\r\n");
      out.write("\r\n");
      out.write("\tmargin:0.5em;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".itemnew {\r\n");
      out.write("\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tbackground-color:#000000;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:250px;\r\n");
      out.write("\tborder:1px solid #5a5a5a;\r\n");
      out.write("\r\n");
      out.write("\tmargin:0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a {\r\n");
      out.write("clear:both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<h1>PRODUCTION STORE</h1>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li><a href=\"login.jsp\">ログイン/新規登録</a></li>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<li><a href=\"\">\tティザーサイトはこちら</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div id=\"menubar\"><ul><li>\r\n");
      out.write("\t\t<a href=\"\">CART(0)</a>\r\n");
      out.write("\t\t</li></ul></div>\r\n");
      out.write("<div class=\"itemnew\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"are\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t<li>aaaaaaaaaaaaaaa</li>\r\n");
      out.write("\t<li>aaaaaaaaaaaaa</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\tCopyright &copy PRODUCTION STORE All rights\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
